### PR TITLE
Update the parso pin

### PR DESCRIPTION
**Pull request by asmeurer**
CC @davidhalter is this correct?

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by asmeurer** [comment]
@davidhalter I can also add you as a maintainer if you like.

**Comment by davidhalter** [comment]
> I can also add you as a maintainer if you like.

Thanks! But I have to decline here. There's already enough work going on with other stuff :)

> CC @davidhalter is this correct?

This is definitely correct. You can also pin it to 0.6.0. That probably even makes more sense (however 0.5.2 is good enough). Generally just looking at the current `requirements.txt` should be telling you what to install.

**Comment by asmeurer** [comment]
FWIW being a maintainer on a conda-forge feedstock doesn't really entail much work. It mostly means you can click merge on update PRs like [this one](https://github.com/conda-forge/jedi-feedstock/pull/27)(which I regrettably did myself without double checking the pins). Hopefully the bot will someday update the pins automatically (CC @CJ-Wright).

**Comment by CJ-Wright** [comment]
Maybe someday...

**Pull request merged**
