### PR TITLE
Rerender + update jedi to 0.11.1

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
New attempt for https://github.com/conda-forge/jedi-feedstock/pull/6 to get jedi updated

Closes https://github.com/conda-forge/jedi-feedstock/issues/7

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by nehaljwani** [comment]
jedi 0.11.1 pins parso==0.1.1
Should we not be doing that?

**Comment by nehaljwani** [comment]
@jorisvandenbossche parso 0.1.1 is available in the conda-forge channel. Any specific reason as to why you are pinning it to 0.1.0 instead of 0.1.1 ?

**Comment by jorisvandenbossche** [comment]
@nehaljwani sorry, I thought jedi only updated that pin on master and not yet for the latest release, but that was a wrong assumption. Edited

**Comment by nehaljwani** [comment]
Actually, I am probably wrong. We may want to re-consider exact pinning, see: https://github.com/AnacondaRecipes/jedi-feedstock/blob/master/recipe/meta.yaml#L27-L29

**Comment by jorisvandenbossche** [comment]
Yes, unless he plans to have micro released of parso not be compatible with different jedi releases, I think it would be better to just not pin.

Shall I copy those lines from the ananconda feedstock?

**Comment by nehaljwani** [comment]
@jorisvandenbossche Yes, I agree with you. We should not pin unless absolutely necessary.

I apologize for going round and coming back to square one.

**Comment by jorisvandenbossche** [comment]
No problem, pin updated again.

I suppose the CIs automatically cancel when updated?

**Comment by nehaljwani** [comment]
For travis, yes, you can see that here: https://travis-ci.org/conda-forge/jedi-feedstock/pull_requests

For appveyor, the job runs a command and aborts itself if there is a new build: 
https://github.com/conda-forge/jedi-feedstock/blob/master/appveyor.yml#L42-L47

**Pull request merged**
