### PR TITLE
update version and sha256 hash for new version

### PR DESCRIPTION
**Pull request by iron0012**

### CODE REVIEW

**Comment by asmeurer** [comment]
Looks like you'll need to add a feedstock for parso first.

**Comment by iron0012** [comment]
Yep, I'm on it right now!

**Comment by jmsdnns** [comment]
It seems as though parso is now represented in feedstock properly. Could someone pick this one up again please? Jedi 0.11.x fixes an issue that results in very significant performance improvements.

**Comment by jmsdnns** [comment]
I suspect all anyone has to do is run the tests again. No code changes necessary from what I can tell.

**Comment by jorisvandenbossche** [comment]
In the meantime there is a 0.11.1, so it can be updated to that directly I think

**Comment by jmsdnns** [comment]
no there isnt.

the latest in conda forge is 10.2. reopen the issue and fix it please.

**Comment by jorisvandenbossche** [comment]
I meant there is a 0.11.1 *jedi release*, while this PR updates it only to 0.11.0

> fix it please.

I don't have the rights to merge this, but you know you can open a PR yourself?

**Pull request closed without merging**
